// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opaaetqdnpgarrojbbla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wYWFldHFkbnBnYXJyb2piYmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Njc5NDQsImV4cCI6MjA2MzA0Mzk0NH0.o_K-dFAI72TE8k0mAWMeiaVpNftVWIbawOfcEx7fIZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);